name: Build and deploy Node.js app to Azure Web App - vscodedeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Upload build artifacts for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            .next
            public
            package.json
            next.config.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download build artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_087A7A4A98F64D239F4FC5C1FA065F27 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2C6C8D518C9E42A1A24165FCDEDBA0FD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_618A9BBA7FB14AA886C934FB6F62200C }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'vscodedeploy'
          slot-name: 'Production'
          package: .

